# Variational Autoencoder (VAE) Configuration

loss_weight:
  kld: 1.0
  mse: 9.0
  class: 0.0

# Encoder
encoder:
  # [from, number, module, args]
  [
    [-1, 1, Conv2d, [3, 32, 5, 1, 2]],
    [-1, 1, BatchNorm2d, [32]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Conv2d, [32, 32, 5, 1, 2]],
    [-1, 1, BatchNorm2d, [32]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Conv2d, [32, 64, 3, 2, 1]],
    [-1, 1, BatchNorm2d, [64]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Conv2d, [64, 64, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [64]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Conv2d, [64, 128, 3, 2, 1]],
    [-1, 1, BatchNorm2d, [128]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Conv2d, [128, 256, 3, 2, 1]],
    [-1, 1, BatchNorm2d, [256]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Conv2d, [256, 512, 3, 2, 1]],
    [-1, 1, BatchNorm2d, [512]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Flatten, []],

    [-1, 1, Linear, [2048, 512]],
    [-1, 1, BatchNorm1d, [512]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Linear, [512, 128]],
    [-1, 1, BatchNorm1d, [128]],
    [-1, 1, LeakyReLU, []],

  ]

# Latent space
latent_space:
  [
    [-1, 1, Linear, [128, 128]],
  ]

classifier:
  [
    [-1, 1, Linear, [128, 32]],
    [-1, 1, BatchNorm1d, [32]],
    [-1, 1, LeakyReLU, []],
    [-1, 1, Linear, [32, 10]],
    [-1, 1, Softmax, []],
  ]

# Decoder
decoder:
  [
    [-1, 1, Linear, [128, 512]],
    [-1, 1, BatchNorm1d, [512]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Linear, [512,2048]],
    [-1, 1, BatchNorm1d, [2048]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Unflatten, [1, [512, 2, 2]]],

    [-1, 1, ConvTranspose2d, [512, 256, 3, 2, 1, 1]],
    [-1, 1, BatchNorm2d, [256]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, ConvTranspose2d, [256, 128, 3, 2, 1, 1]],
    [-1, 1, BatchNorm2d, [128]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, ConvTranspose2d, [128, 64, 3, 2, 1, 1]],
    [-1, 1, BatchNorm2d, [64]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, ConvTranspose2d, [64, 64, 3, 1, 1, 0]],
    [-1, 1, BatchNorm2d, [64]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, ConvTranspose2d, [64, 32, 3, 2, 1, 1]],
    [-1, 1, BatchNorm2d, [32]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, ConvTranspose2d, [32, 32, 3, 1, 1, 0]],
    [-1, 1, BatchNorm2d, [32]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, ConvTranspose2d, [32, 3, 3, 1, 1, 0]],
    [-1, 1, BatchNorm2d, [3]],
    [-1, 1, LeakyReLU, []],
  ]
