# Variational Autoencoder (VAE) Configuration

# Encoder
encoder:
  # [from, number, module, args]
  [
    [-1, 1, Conv2d, [3, 64, 5, 1, 2]],
    [-1, 1, BatchNorm2d, [64]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, MaxPool2d, [2,2]],

    [-1, 1, Conv2d, [64, 128, 5, 1, 2]],
    [-1, 1, BatchNorm2d, [128]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, MaxPool2d, [2,2]],

    [-1, 1, Conv2d, [128, 256, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [256]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, MaxPool2d, [2,2]],

    [-1, 1, Conv2d, [256, 256, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [256]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Conv2d, [256, 256, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [256]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Flatten, []],

  ]

# Latent space
latent_space:
  [
    [-1, 1, Linear, [ 4096, 4096]],  # Fully connected layer
  ]

# Decoder
decoder:
  [
    [-1, 1, Linear, [ 4096, 4096]],
    [-1, 1, LeakyReLU, []],

    [ -1, 1, Linear, [ 4096, 4096] ],
    [ -1, 1, LeakyReLU, [ ] ],

    [ -1, 1, Linear, [ 4096, 4096] ],
    [ -1, 1, LeakyReLU, [] ],

    [-1, 1, Unflatten, [1, [256, 4, 4]]],

    [-1, 1, ConvTranspose2d, [256, 256, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [256]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Upsample, [8]],

    [-1, 1, ConvTranspose2d, [256, 128, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [128]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Upsample, [16]],

    [-1, 1, ConvTranspose2d, [128, 64, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [64]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, ConvTranspose2d, [64, 64, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [64]],
    [-1, 1, LeakyReLU, []],

    [-1, 1, Upsample, [32]],

    [-1, 1, ConvTranspose2d, [64, 3, 3, 1, 1]],
    [-1, 1, BatchNorm2d, [3]],
    [-1, 1, LeakyReLU, []],
  ]
